<?php
/** @var MercadoPago\Core\Block\Calculator\CalculatorForm $block */
const STATUS_ACTIVE = 'active';
const PAYMENT_TYPE_CREDIT_CARD = 'credit_card';

$list = $this->getPaymentMethods();
$pk = $this->getPublicKey();
$amount = $this->getAmount();

$isSecure = $this->isCurrentlySecure();

?>
<div id="mercadopago-popup" class="mercadopago-popup" style="display: none;">
    <div class="mercadopago-popup-overlay" onclick="MercadoPagoCustomCalculator.hidePopup()"></div>
    <main role="main">
        <div class="btn-close-popup" onclick="MercadoPagoCustomCalculator.hidePopup()">X</div>
        <?php if (!empty($list) & !empty($pk)) : ?>
            <section id="id-order-profile-app-wrapper" class="order-profile-app-wrapper" data-component="paymentCalculator">
                <div class="loading-overlay"> </div>
                <div class="payment-titles">
                    <!--            'Pagar con Mercado Pago'-->
                    <h2 class="title-border-line"><?php /* @escapeNotVerified */ echo __('Pay with MercadoPago')?></h2>
                    <!--            'Tarjeta de crédito'-->
                    <h3 id="title-payment-cards"><?php /* @escapeNotVerified */ echo __('Payment cards')?></h3>
                </div>

                <div class="columns">
                    <div class="cards-column">
                        <ul id="op-payment-cards-list">
                            <?php foreach ($list as $i) { ?>
                                <?php if ($i['status'] === STATUS_ACTIVE & $i['payment_type_id'] === PAYMENT_TYPE_CREDIT_CARD): ?>
                                    <li id="<?php echo $block->escapeQuote($i['id']); ?>-li">
                                        <label for="<?php echo $block->escapeQuote($i['id']); ?>">
                                            <input id="<?php echo $block->escapeQuote($i['id']); ?>" type="radio" name="paymentMethods" value="<?php echo $i['id']; ?>" />
                                            <?php if ($isSecure): ?>
                                                <img src="<?php echo $block->escapeQuote($i['secure_thumbnail']); ?>" alt="<?php echo $i['id']; ?>"/>
                                            <?php else : ?>
                                                <img src="<?php echo $block->escapeQuote($i['thumbnail']); ?>" alt="<?php echo $i['id']; ?>"/>
                                            <?php endif; ?>
                                        </label>
                                    </li>
                                <?php endif; ?>
                            <?php } ?>
                        </ul>
                    </div>

                    <div class="data-column">
                        <div id="paymentCost" class="op-section-actions price-conditions ">
                            <div id="op-bank-select">
                                <label for="issuerSelect"><?php /* @escapeNotVerified */ echo __('Bank')?></label>
                                <select id="issuerSelect"></select>
                            </div>

                            <div class="op-installments" id="finalPrice" data-state="visible">
                                <label for="installmentSelect"><?php /* @escapeNotVerified */ echo __('Pay')?></label>
                                <select id="installmentSelect" name="installmentSelect" class="installmentSelect"></select>
                                <span id="installmentX">x</span>
                                <div class="op-price-box">
                                    <span id="installmentsPrice" class="op-price ch-price"></span>
                                    <strong id="installmentsInterestFreeText" class="op-installments-free-text stand-out">
                                        <!-- remove if interest free -->
                                        <?php /* @escapeNotVerified */ echo __('Interest-free')?>
                                    </strong>
                                </div>
                            </div>
                        </div>

                        <div class="op-submit">
                            <input id="selectPayment" type="button" class="ch-btn ch-btn-small button action primary calculatorTriggerHide" value="Aceptar">
                        </div>

                        <div id="costTransparentPrices" data-state="visible">
                            <div class="op-installments-primary-options">
                                <span id="installmentCFT">CTF:</span>
                            </div>

                            <div class="op-installments-secondary-options">
                                <div class="op-installments-section">
                                    <span class="op-installments-title">PTF:</span>
                                    <span id="installmentPTF"></span>
                                </div>
                                <div class="op-installments-section">
                                    <span class="op-installments-title"></span>
                                    <span id="installmentTEA">TEA:</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        <?php else : ?>
            <h2> <?php /* @escapeNotVerified */ echo __('XXXXXXXX')?> </h2>
        <?php endif; ?>
    </main>

    <script type="text/javascript">
        var PublicKeyMercadoPagoCustom = '<?php /* @escapeNotVerified */ echo $pk; ?>';
        var AllPaymentMethods = '<?php /* @escapeNotVerified */ echo json_encode($list); ?>';
        var Amount = '<?php /* @escapeNotVerified */ echo $amount ?>';
    </script>
    <script>
        require(['MPcustom', 'tinyj', 'tiny', 'meli', 'calculator'],
            function() {
                MercadoPagoCustomCalculator.getCalculator();
            }
        );

    </script>
</div>

