<?php
/**
 * @var MercadoPago\Core\Block\Custom\Success $block
 */
    $order = $this->getOrder();
    $total = $this->getTotal();
    $payment = $this->getPayment();
    
    //monta link para o pedido
$link_to_order = __('Your order %1 has been successfully generated.', '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>');
    
    $payment_method = $this->getPaymentMethod();
    $info_payment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if(!isset($info_payment['status']['value'])): ?>
        <h2 class="mercadopago-title"><?php /* @escapeNotVerified */ echo __('Thank you for your purchase!'); ?></h2>
        <p><?php /* @escapeNotVerified */ echo $link_to_order; ?></p>
    <?php else: ?>
        <?php
            $message_status = $this->getMessageByStatus(
                $info_payment['status']['value'],
                $info_payment['status_detail']['value'],
                (isset($info_payment['payment_method']['value'])) ? $info_payment['payment_method']['value'] : '',
                (isset($info_payment['installment']['value'])) ? $info_payment['installment']['value'] : '' ,
                $this->getTotal()
            );
        ?>
        <h2 class="mercadopago-title"><?php echo $block->escapeHtml($message_status['title']); ?></h2>

        <p><?php echo $block->escapeHtml($message_status['message']); ?></p>

        <p><?php /* @escapeNotVerified */ echo $link_to_order; ?></p>

        <h3 class="mercadopago-title-info-payment"><?php /* @escapeNotVerified */ echo __('Payment information'); ?></h3>

        <?php foreach($info_payment as $info): ?>
            <p><?php /* @escapeNotVerified */ echo __($info['text']); ?></p>
        <?php endforeach; ?>
            
    <?php endif; ?>
</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png" /> 
</div>


<div class="primary button-success">
    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
</div>

