<?php
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$link_to_order = __('Your order %1 has been successfully generated.', '<a href="' . $this->getOrderUrl() . '">' . $order->getIncrementId() . '</a>');

$payment_method = $this->getPaymentMethod();
$info_payment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if (!isset($info_payment['status']['value'])): ?>
        <h2 class="mercadopago-title">
            <?php echo __('Thank you for your purchase!'); ?>
        </h2><p><?php echo $link_to_order; ?></p>
    <?php else: ?><?php
        $message_status = $this->getMessageByStatus(
            $info_payment['status']['value'],
            $info_payment['status_detail']['value'],
            $info_payment['payment_method']['value'],
            $info_payment['installment']['value'],
            $this->getTotal()
        );
        ?>
        <h2 class="mercadopago-title"><?php echo $message_status['title']; ?></h2>

        <p><?php echo $message_status['message']; ?></p>

        <p><?php echo $link_to_order; ?></p>

        <h5 class="mercadopago-title-info-payment"><?php echo __('Payment information'); ?></h5>

        <?php foreach ($info_payment as $info): ?>
            <p><?php echo $info['text']; ?></p>
        <?php endforeach; ?>

    <?php endif ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>
