<?php
const STATUS_ACTIVE = 'active';
const PAYMENT_TYPE_CREDIT_CARD = 'credit_card';

$list = $this->getPaymentMethods();
$pk = $this->getPublicKey();
?>

<main id="popup-modal" role="main">

    <style>
        /* todo move it to style file */
        .order-profile-app-wrapper .loading-overlay {
            display: none;
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: gray;
            opacity: 0.5;
        }
        .order-profile-app-wrapper.loading .loading-overlay {
            display: block;
        }
    </style>

    <?php if (!empty($list) & !empty($pk)) : ?>
    <section id="id-order-profile-app-wrapper" class="order-profile-app-wrapper" data-component="paymentCalculator">
        <div class="loading-overlay"> </div>
        <div class="op-section-payment">
            <!--            'Pagar con Mercado Pago'-->
            <h2 class="title-border-line"><?php echo __('Pay with MercadoPago')?></h2>
            <!--            'Tarjeta de crédito'-->
            <h3 id="title-payment-cards"><?php echo  __('Payment cards')?></h3>
            <ul id="op-payment-cards-list">
                <?php foreach ($list as $i) { ?>
                    <?php if ($i['status'] === STATUS_ACTIVE & $i['payment_type_id'] === PAYMENT_TYPE_CREDIT_CARD): ?>
                        <li>
                            <input id="<?php echo $i['id']; ?>" type="radio" name="paymentMethods" value="<?php echo $i['id']; ?>" />
                                <img  src="<?php echo $i['thumbnail']; ?>" alt="<?php echo $i['id']; ?>"/>
                        </li>
                    <?php endif; ?>
                <?php } ?>
            </ul>
        </div>
        <div id="op-bank-select">
            <label>
                <?php echo __('Banck')?>
            </label>
            <select id="issuerSelect">
            </select>
        </div>
        <div id="paymentCost" class="op-section-actions price-conditions ">

            <div class="op-installments" id="finalPrice" data-state="visible">
                <span><?php echo __('Pay')?>:</span>

                <select id="installmentSelect" name="installmentSelect" class="installmentSelect">
                </select>

                <span id="installmentX">x </span>
                <span id="installmentsPrice" class="op-price ch-price">
                </span>

                <strong id="installmentsInterestFreeText" class="op-installments-free-text stand-out">
                <!-- remove if interest free -->
                    <?php echo __('Interest-free')?>
                </strong>

                <div id="costTransparentPrices" data-state="visible">
                    <div class="op-installments-secondary-options">
                        <span class="op-installments-title">PTF:</span>
                        <span id="installmentPTF">
                        </span>

                        <span class="op-installments-title"></span>
                        <span id="installmentTEA">
                        </span>
                    </div>

                    <div class="op-installments-primary-options">
                        <span id="installmentCFT">
                        </span>
                    </div>
                </div>
            </div>

            <p class="op-submit">
                <input id="selectPayment" type="button" class="ch-btn ch-btn-small" value="Aceptar" onclick=" ">
            </p>
        </div>
    </section>
    <?php else : ?>
        <h2> <?php echo __('XXXXXXXX')?> </h2>
    <?php endif; ?>
</main>

<script type="text/javascript">
    var PublicKeyMercadoPagoCustom = '<?php echo $pk; ?>';
    var AllPaymentMethods = '<?php echo json_encode($list); ?>';
    var Amount = '<?php echo $this->getAmount(); ?>';
</script>

<script>
    require(['MPcustom', 'tinyj', 'tiny', 'meli', 'calculator'],
        function() {
            MercadoPagoCustomCalculator.getCalculator();
        }
    );

</script>


