<script type="text/javascript" src="https://secure.mlstatic.com/modules/javascript/analytics.js"></script>
<script>
    var data = <?php echo json_encode($this->getPaymentData()) ?>;
    if (data !== null ) {
        var MA = ModuleAnalytics;
        if (data.public_key !== undefined) {
            MA.setPublicKey(data.public_key);
            MA.setToken(null);
        } else {
            MA.setToken(data.analytics_key);
            MA.setPublicKey(null);
        }
        MA.setPaymentId(data.payment_id.toString());
        MA.setPaymentType(data.payment_type);
        MA.setCheckoutType(data.checkout_type);
        MA.put();
    }
</script>