<?php
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$linkToOrder = $this->__('Your order %1 has been successfully generated.', '<a href="' . $this->getOrderUrl() . '">' . $order->getIncrementId() . '</a>');

$paymenMethod = $this->getPaymentMethod();
$infoPayment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if (!isset($infoPayment['status']['value'])): ?>
        <h2 class="mercadopago-title">
            <?php echo $this->__('Thank you for your purchase!'); ?>
        </h2><p><?php echo $linkToOrder; ?></p>
    <?php else: ?><?php
        $message_status = $this->getMessageByStatus(
            (isset($infoPayment['status']['value'])?$infoPayment['status']['value']:''),
            (isset($infoPayment['status_detail']['value']))?$infoPayment['status_detail']['value']:'',
            (isset($infoPayment['payment_method']['value']))?$infoPayment['payment_method']['value']:'',
            (isset($infoPayment['installment']['value']))?$infoPayment['installment']['value']:'',
            $this->getTotal()
        );
        ?>
        <h2 class="mercadopago-title"><?php echo $message_status['title']; ?></h2>

        <p><?php echo $message_status['message']; ?></p>

        <p><?php echo $linkToOrder; ?></p>

        <h3 class="mercadopago-title-info-payment"><?php echo $this->__('Payment information'); ?></h3>

        <?php foreach ($infoPayment as $info): ?>
            <p><?php echo $this->__($info['text']); ?></p>
        <?php endforeach; ?>

    <?php endif ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>


    <div class="primary button-success">
        <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
    </div>

