<?php
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();

$link_to_order = __('Your order %1 has been successfully generated.', '<a href="' . $this->getOrderUrl() . '">' . $order->getIncrementId() . '</a>');

$payment_method = $this->getPaymentMethod();
$info_payment = $this->getInfoPayment();
?>

<div id="box-mercadopago">

    <?php if ($payment_method == 'mercadopago_customticket'): ?>
        <h2 class="mercadopago-title"><?php echo __('Thank you for your purchase!'); ?></h2>

        <p>
            <?php echo $link_to_order; ?>
        </p>

        <p>
            <?php echo('Generate the ticket and pay it wherever you want.'); ?>
        </p><p>
            <?php echo __('Will be approved within 2 business days.'); ?>
        </p>
        <a href="<?php echo urldecode($this->escapeHtml($payment->getAdditionalInformation('activation_uri'))); ?>" target="_blank" id="btn-boleto-mercadopago">
            <?php echo __('Generate Ticket'); ?>
        </a>

    <?php endif; ?>

</div>

<div id="logo-mercadopago">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>

<div class="primary button-success">
    <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
</div>
